-- Modules present in CLASSICDEV but missing from CLASSICTRIAL (CLASSICNEW.MODULE)
-- Generated 2026-10-01 from CLASSICDEV. Run on CLASSICTRIAL as CLASSICNEW. Re-runnable:
-- a row is skipped if its MENU_TABLE is already there. ID keeps the CLASSICDEV value
-- unless TRIAL already uses it, then MAX(ID)+1.
SET DEFINE OFF

-- DEV ID 3: Workforce & Payroll - Garden Payroll
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 3) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 3 END,
       'Workforce & Payroll - Garden Payroll', 'VBMENU_GP_PAYROLL', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'GP', 'USRACS_GARDEN_PAYROLL', NULL, 'MVC', NULL, NULL, 'Y'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_GP_PAYROLL'));

-- DEV ID 4: Tea Sales & Export Management
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 4) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 4 END,
       'Tea Sales & Export Management', 'VBMENU_TEA_SALES', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'TS', 'USRACS_TEA_SALES', NULL, 'MVC', NULL, NULL, NULL
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_TEA_SALES'));

-- DEV ID 8: Packet Tea Sales Management
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 8) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 8 END,
       'Packet Tea Sales Management', 'VBMENU_PACKET_TEA', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'PT', 'USRACS_PACKET_TEA', 'JST', 'MVC', NULL, NULL, NULL
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_PACKET_TEA'));

-- DEV ID 11: Exectuive / Staff Payroll - Head office
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 11) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 11 END,
       'Exectuive / Staff Payroll - Head office', 'VBMENU_HP_PAYROLL', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'GP', 'USRACS_HO_PAYROLL', NULL, 'MVC', NULL, NULL, NULL
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_HP_PAYROLL'));

-- DEV ID 14: Warehouse Management
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 14) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 14 END,
       'Warehouse Management', 'VBMENU_WAREHOUSE', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'WH', 'USRACS_WAREHOUSE', NULL, 'MVC', NULL, NULL, NULL
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_WAREHOUSE'));

-- DEV ID 15: Fixed/Block Asset Management
INSERT INTO CLASSICNEW.MODULE (ID, MODULE_NAME, MENU_TABLE, CONTROL_TABLE, MENU_SORT_BY, PERMISSION, MODULE_CODE, USRACS_TABLE, LOCA, TECHNOLOGY, HOME_PAGE, LOGOUT_PAGE, IS_SUBMENU)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE ID = 15) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.MODULE) ELSE 15 END,
       'Fixed/Block Asset Management', 'VBMENU_BLOCK', 'CLASSIC_CONTROL', 'JAG1', 'Y', 'FB', 'USRACS_HOSALES', NULL, 'MVC', NULL, NULL, NULL
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.MODULE WHERE UPPER(MENU_TABLE) = UPPER('VBMENU_BLOCK'));

COMMIT;
