-- 9 row(s) of CLASSICNEW.USER_SCHEMA_LINK where USR_ID like 'FACT_JSTIL2027', from CLASSICDEV (generated 2026-10-01)
-- Re-runnable: a row is skipped if (USER_ORA, USR_ID, UNIT, MODULE_CODE) already exists.
-- ID keeps the CLASSICDEV value unless the target already uses it, then MAX(ID)+1.
SET DEFINE OFF

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3081) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3081 END,
       'JST', 'JSTI', 'CORELOCK', 'FACT_JSTIL2027', 'Packet Tea Sales Management', TO_DATE('2026-09-30 11:43:48','YYYY-MM-DD HH24:MI:SS'), '11:43', NULL, NULL, NULL, NULL, NULL, 'CLASSICNEW', 1, 'PT', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORELOCK' AND USR_ID = 'FACT_JSTIL2027' AND UNIT = 'JSTI' AND MODULE_CODE = 'PT');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3021) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3021 END,
       'JST', 'JSTI', 'COREPT', 'FACT_JSTIL2027', 'Packet Tea Sales Management', TO_DATE('2026-08-28 11:55:50','YYYY-MM-DD HH24:MI:SS'), '11:55', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'PT', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'COREPT' AND USR_ID = 'FACT_JSTIL2027' AND UNIT = 'JSTI' AND MODULE_CODE = 'PT');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2921) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2921 END,
       'JST', 'JSTI', 'CORETEAM', 'FACT_JSTIL2027', 'Packet Tea Sales Management', TO_DATE('2026-08-28 11:55:50','YYYY-MM-DD HH24:MI:SS'), '11:55', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'PT', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'FACT_JSTIL2027' AND UNIT = 'JSTI' AND MODULE_CODE = 'PT');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3101) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3101 END,
       'JST', 'JSTI', 'CORETEAM', 'FACT_JSTIL2027', 'Fixed/Block Asset Management', TO_DATE('2026-08-28 11:55:50','YYYY-MM-DD HH24:MI:SS'), '11:55', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'FB', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'FACT_JSTIL2027' AND UNIT = 'JSTI' AND MODULE_CODE = 'FB');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2741) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2741 END,
       'JST', NULL, 'CORETEAM', 'FACT_JSTIL2027', 'Tea Sales & Export Management', TO_DATE('2020-06-25 00:00:00','YYYY-MM-DD HH24:MI:SS'), '09:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'TS', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'FACT_JSTIL2027' AND UNIT IS NULL AND MODULE_CODE = 'TS');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2742) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2742 END,
       'JST', NULL, 'CORETEAM', 'FACT_JSTIL2027', 'WAREHOUSE', TO_DATE('2020-06-25 00:00:00','YYYY-MM-DD HH24:MI:SS'), '09:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'WH', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'FACT_JSTIL2027' AND UNIT IS NULL AND MODULE_CODE = 'WH');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2941) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2941 END,
       'JST', NULL, 'CORETEAM', 'FACT_JSTIL2027', 'Tea Sales & Export Management', TO_DATE('2026-09-02 13:20:28','YYYY-MM-DD HH24:MI:SS'), '13:20', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'TS', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'FACT_JSTIL2027' AND UNIT IS NULL AND MODULE_CODE = 'TS');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3022) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3022 END,
       'JST', 'JSTI', 'CORETT', 'FACT_JSTIL2027', 'Packet Tea Sales Management', TO_DATE('2026-08-28 11:55:50','YYYY-MM-DD HH24:MI:SS'), '11:55', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'PT', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETT' AND USR_ID = 'FACT_JSTIL2027' AND UNIT = 'JSTI' AND MODULE_CODE = 'PT');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2801) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2801 END,
       'JST', NULL, 'PINAK', 'FACT_JSTIL2027', 'TEA SALES', TO_DATE('2026-04-02 00:00:00','YYYY-MM-DD HH24:MI:SS'), '09:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'SH', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'PINAK' AND USR_ID = 'FACT_JSTIL2027' AND UNIT IS NULL AND MODULE_CODE = 'SH');

COMMIT;
