-- 3 row(s) of CLASSICNEW.USER_SCHEMA_LINK where USR_ID = 'PAY_BOUGHTLEAF2027', from CLASSICDEV (generated 2026-10-01)
-- Re-runnable: a row is skipped if (USER_ORA, USR_ID, UNIT) already exists.
-- ID keeps the CLASSICDEV value unless the target already uses it, then MAX(ID)+1.
SET DEFINE OFF

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 2901) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 2901 END,
       'JST', 'DEWN', 'CORETEAM', 'PAY_BOUGHTLEAF2027', 'Workforce & Payroll - Bought Leaf', TO_DATE('2026-06-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), '9:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'BP', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'CORETEAM' AND USR_ID = 'PAY_BOUGHTLEAF2027' AND UNIT = 'DEWN');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3042) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3042 END,
       'JST', 'DEWN', 'GANESH', 'PAY_BOUGHTLEAF2027', 'Workforce & Payroll - Bought Leaf', TO_DATE('2026-06-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), '9:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'BP', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'GANESH' AND USR_ID = 'PAY_BOUGHTLEAF2027' AND UNIT = 'DEWN');

INSERT INTO CLASSICNEW.USER_SCHEMA_LINK (ID, LOCA, UNIT, USER_ORA, USR_ID, MODULE_NAME, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DTAG, MACHINE_NO, USER_ENT, API_ALLOW, MODULE_CODE, TECHNOLOGY)
SELECT CASE WHEN EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE ID = 3041) THEN (SELECT NVL(MAX(ID),0)+1 FROM CLASSICNEW.USER_SCHEMA_LINK) ELSE 3041 END,
       'JST', 'DEWN', 'DIPONJEET', 'PAY_BOUGHTLEAF2027', 'Workforce & Payroll - Bought Leaf', TO_DATE('2026-06-01 00:00:00','YYYY-MM-DD HH24:MI:SS'), '9:00', NULL, NULL, NULL, NULL, 'RajLaptop', NULL, 1, 'BP', 'MVC'
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.USER_SCHEMA_LINK WHERE USER_ORA = 'DIPONJEET' AND USR_ID = 'PAY_BOUGHTLEAF2027' AND UNIT = 'DEWN');

COMMIT;
