-- 2 row(s) of PAY_BOUGHTLEAF2027.USRACS_BLF_PAYROLL where USER_ORA = 'CORETEAM', from CLASSICDEV (generated 2026-10-01)
SET DEFINE OFF

INSERT INTO PAY_BOUGHTLEAF2027.USRACS_BLF_PAYROLL (LOCA, UNIT, UID_ORA, MNUID, INDEX_ORA, AEDV, EDAY, ADAY, USER_ORA, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DDAY, USER_NAME, USER_ENTDT, USER_NAME_NEW, USER_ENTDT_NEW, OS_USER, TERMINAL_ID, DTAG, SCHEMA_NM, LOCKEDBYUSERID, LOCKEDUNTIL)
VALUES ('JST', NULL, 'CORETEAM', 'MAST_ASS', '20', NULL, NULL, NULL, 'CORETEAM', TO_DATE('2026-09-04 14:09:00','YYYY-MM-DD HH24:MI:SS'), '14:09', NULL, NULL, NULL, NULL, 'CORETEAM', TO_DATE('2026-09-04 14:09:00','YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 'SERVER', 'SCRIPT', NULL, 'PAY_BOUGHTLEAF2027', NULL, NULL);
INSERT INTO PAY_BOUGHTLEAF2027.USRACS_BLF_PAYROLL (LOCA, UNIT, UID_ORA, MNUID, INDEX_ORA, AEDV, EDAY, ADAY, USER_ORA, ENTDT, TIME_ORA, USER_NEW, ENTDT_NEW, TIME_NEW, DDAY, USER_NAME, USER_ENTDT, USER_NAME_NEW, USER_ENTDT_NEW, OS_USER, TERMINAL_ID, DTAG, SCHEMA_NM, LOCKEDBYUSERID, LOCKEDUNTIL)
VALUES ('JST', NULL, 'CORETEAM', 'MAST_ASS', '21', NULL, NULL, NULL, 'CORETEAM', TO_DATE('2026-09-04 14:09:00','YYYY-MM-DD HH24:MI:SS'), '14:09', NULL, NULL, NULL, NULL, 'CORETEAM', TO_DATE('2026-09-04 14:09:00','YYYY-MM-DD HH24:MI:SS'), NULL, NULL, 'SERVER', 'SCRIPT', NULL, 'PAY_BOUGHTLEAF2027', NULL, NULL);

COMMIT;
