/* =====================================================================
   Enable "Tea Procurement" -> "Tea Purchase Debit Note" / "Tea Purchase
   Credit Note" (VBMENU_PACKET_TEA ORDERCODEs 01021020T / 01021030T) on the
   TeaPurchaseNote controller (VB6 trn_credit_note.frm, TRAN_CODE 36 / 37).
   Idempotent: each insert is skipped if the menu code is already mapped.
   Applied to CLASSICNEW on 2026-09-19 as IDs 373 / 374.
   ===================================================================== */

INSERT INTO CLASSICNEW.VBMENU_DONE (ID, PROJECTNAME, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, IS4SUBDOMAIN, MODULECODE, ISACTIVE)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CLASSICNEW.VBMENU_DONE), 'PT', 'Tea Purchase Debit Note', '01021020T', 'TeaPurchaseNote', 'DebitNote', 1, 'PT', 1
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE = '01021020T' AND MODULECODE = 'PT');

INSERT INTO CLASSICNEW.VBMENU_DONE (ID, PROJECTNAME, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, IS4SUBDOMAIN, MODULECODE, ISACTIVE)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CLASSICNEW.VBMENU_DONE), 'PT', 'Tea Purchase Credit Note', '01021030T', 'TeaPurchaseNote', 'CreditNote', 1, 'PT', 1
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE = '01021030T' AND MODULECODE = 'PT');

SELECT ID, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, ISACTIVE
  FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE IN ('01021020T', '01021030T');

COMMIT;
