/* =====================================================================
   Enable "Tea Manufacturing / Sale" -> "Packet Tea Debit Note" / "Packet Tea
   Credit Note" (VBMENU_PACKET_TEA ORDERCODEs 01030050T / 01030060T) on the
   PacketTeaNote controller (VB6 trn_credit_note.frm, TRAN_CODE 34 / 35).
   Idempotent: each insert is skipped if the menu code is already mapped.
   Applied to CLASSICNEW on 2026-09-21 as IDs 375 / 376.
   ===================================================================== */

INSERT INTO CLASSICNEW.VBMENU_DONE (ID, PROJECTNAME, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, IS4SUBDOMAIN, MODULECODE, ISACTIVE)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CLASSICNEW.VBMENU_DONE), 'PT', 'Packet Tea Debit Note', '01030050T', 'PacketTeaNote', 'DebitNote', 1, 'PT', 1
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE = '01030050T' AND MODULECODE = 'PT');

INSERT INTO CLASSICNEW.VBMENU_DONE (ID, PROJECTNAME, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, IS4SUBDOMAIN, MODULECODE, ISACTIVE)
SELECT (SELECT NVL(MAX(ID), 0) + 1 FROM CLASSICNEW.VBMENU_DONE), 'PT', 'Packet Tea Credit Note', '01030060T', 'PacketTeaNote', 'CreditNote', 1, 'PT', 1
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE = '01030060T' AND MODULECODE = 'PT');

SELECT ID, MENUNAME, MENUCODE, CONTROLLER, ACTIONMETHOD, ISACTIVE
  FROM CLASSICNEW.VBMENU_DONE WHERE MENUCODE IN ('01030050T', '01030060T');

COMMIT;
